### ISSUE TITLE
Build script fails

### ISSUE THREAD

**Issue by cenobitedk** [arberg/docker-ihccaptain#3]
Thanks for your work!

However, was going to update my local image which I run on a RPI 4. The latest on docker hub can't run on arm, so I need to build it.

This is the build output:
```
$ sudo ./build.sh
+ . env.sh
++ set -ex
++ USERNAME=arberg
++ IMAGE=ihccaptain
+++ cat VERSION
++ VERSION=1.48-arm
+++ dirname ./build.sh
++ cd .
++ pwd -P
+ BASE_DIR=/home/pirate/ihccaptain/source/1.48
+ chmod 755 /home/pirate/ihccaptain/source/1.48/host/run_ihc_captain_in_docker.sh
+ [[ '' = \-\-\n\o\-\c\a\c\h\e ]]
+ echo '########### Building using build-cache ###########'
########### Building using build-cache ###########
+ docker build -t arberg/ihccaptain:latest .
Sending build context to Docker daemon  240.6kB
Step 1/14 : FROM ubuntu:18.04
 ---> 154a1aa86195
Step 2/14 : RUN apt-get update && apt-get install -y cron
 ---> Using cache
 ---> f4ce8689e14f
Step 3/14 : RUN apt-get update && apt-get install -y software-properties-common
 ---> Using cache
 ---> 0ecba4462d8e
Step 4/14 : RUN	apt-add-repository -y ppa:ondrej/php
 ---> Using cache
 ---> e650f8427700
Step 5/14 : COPY VERSION .
 ---> Using cache
 ---> 1b2fb354ef44
Step 6/14 : COPY host/.bash_aliases /root
 ---> Using cache
 ---> 772397fbba3e
Step 7/14 : ADD http://jemi.dk/ihc/files/install /tmp/install
Downloading [==================================================>]  33.37kB/33.37kB
 ---> Using cache
 ---> 8e6147e9efac
Step 8/14 : RUN chmod 755 /tmp/install
 ---> Using cache
 ---> 1f7e4199c1cc
Step 9/14 : RUN ["/bin/bash", "-c", "/tmp/install docker"]
 ---> Running in f7dd03dae091
IHC Captain custom installer for Docker...






\u25BA\u25BA\u25BA IHC Captain

Starter installationen - vent venligst, det kan tage lang tid...

Opdatering af software arkiv...
[  OK  ] Opdatering af software arkiv
Installere ekstra programmer...
[  OK  ] Installere ekstra programmer
Installere webserver, nginx...
[  OK  ] Installere webserver, nginx
Installere PHP 7.3...
[  OK  ] Installere PHP 7.3
Oprydning af software arkiv...
[  OK  ] Oprydning af software arkiv
Fjerner gamle programmer...
[  OK  ] Fjerner gamle programmer
[  OK  ] Tilføjer root brugeren til www-data gruppen
[  OK  ] Opretter mappen /opt/ihccaptain
[  OK  ] Henter IHC Captain(ihccaptain.tar.gz)
[  OK  ] Udpakker IHC Captain
Unable to find PHP Socket fatal error


The command '/bin/bash -c /tmp/install docker' returned a non-zero code: 1
```

Does it tell anything towards troubleshooting the problem?

I running [HypriotOS](https://github.com/hypriot) v1.11.4 - https://github.com/hypriot/image-builder-rpi/releases/tag/v1.11.4
It's not the latest (v1.12.3).

Let me know if there's anything I can do to debug the failed build. 
Thanks

**Comment by arberg** [comment]
Hi, I get same error-message. I'll try contacting Mikkel and see if he knows something. Here's some info if you want to debug it yourself, or if that becomes relevant later:

It seems IHC captain install script fails on the docker. This is on how to debug that issue from within the docker.

The build executes the `Dockerfile`.The output says its executing 9th non-empty line, ie:
`RUN ["/bin/bash", "-c", "/tmp/install docker"]`

The /tmp/install docker is downloaded from http://jemi.dk/ihc/files/install in a few lines above.

you can out-comment everything from that line and below, and execute build, then run the docker container with bash, like they show here: https://subscription.packtpub.com/book/virtualization_and_cloud/9781787286986/6/ch06lvl1sec38/debugging-a-dockerfile

Then I would run the install script from within the container, and try to debug it. When I do that I typically mount the script from host filesystem, so its easy to edit script and rerun within docker, adding print-lines etc. 

Alex

**Comment by arberg** [comment]
It looks like v1.49 is the last which worked, but it seems we don't have access to previous installer script versions on jemi.dk. It would be easier for you to start with something that worked.

**Comment by arberg** [comment]
I've fixed the script, so now it works again on docker. I'm using my custom version of the installer in this github project, until Mikkel updates the 'live' script, which I think he'll do soon.

**Comment by cenobitedk** [comment]
Thank you @arberg!
I did use continue to use my old 1.40-arm custom build until the latest version would run.
The internal IHC Captain update check did report 1.52 being available and said I was on 1.49. The update failed, but upon page reload I could see that it had in fact updated to 1.52. I'm not sure if the update will persist when the container is restarted?

**Comment by arberg** [comment]
If you pull the latest image it should run. 

In-container update of IHCCaptain has never worked previously. It's possible it works now with the 1.52 installer script update, I don't know.

You won't lose changes made within the container by restarting the container, only by deleting it and starting fresh from the image. Well unless you always delete the container when you stop it like with `docker run --rm`

**Comment by cenobitedk** [comment]
Just confirmed that it worked perfectly 👍  thanks!

A little surprised that it also started the container, but it's cool!
